name: CMake action build example test

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:      
    - uses: lukka/get-cmake@latest

    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      
    - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/.examples/CMake/CMakeLists.txt'
        configurePreset: 'release'
        buildPreset: 'release'
        vcpkgGitCommitId: ''

    - name: Upload artifacts to see what's going on
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-artifact
        path: build
        include-hidden-files: 'true'