name: CMake action build example test

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "windows", os: windows-latest, cc: "cl", cxx: "cl", ext: ".exe" }
          - { name: "ubuntu", os: ubuntu-latest, cc: "gcc", cxx: "g++", ext: "" }
          - { name: "macos", os: macos-latest, cc: "clang", cxx: "clang++", ext: "" }

    steps:
    - uses: actions/checkout@v4

    - uses: lukka/get-cmake@latest

    - name: Get and save latest vcpkg commit to json config
      id: vcpkg
      shell: bash
      run: |
        COMMIT_ID=$(git ls-remote https://github.com/microsoft/vcpkg  HEAD | awk '{ print $1}')
        echo "Latest commit on VCPKG: $COMMIT_ID"
        echo "commit=$COMMIT_ID" >> $GITHUB_OUTPUT
        
    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ steps.vcpkg.outputs.commit }}
      
    - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/.examples/CMake/CMakeLists.txt'
        configurePreset: 'release'
        buildPreset: 'release'
        buildPresetAdditionalArgs: '--log-level=DEBUG'
        configurePresetAdditionalArgs: '-DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}'

    - name: Upload artifacts to see what's going on
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.config.os }}-artifact
        path: build
        include-hidden-files: 'true'