name: CMake action build example test

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ] # [ windows-latest, ubuntu-latest, macos-latest ]
    steps:  
      - name: Setup VCPKG
        id: vcpkg
        shell: bash
        run: |
          git clone https://github.com/microsoft/vcpkg.git ${{github.workspace}}/vcpkg
          
          #echo "path=${{github.workspace}}/vcpkg" >> $GITHUB_OUTPUT
          
          echo "VCPKG_ROOT=\"${{github.workspace}}/vcpkg\"" >> $GITHUB_ENV
          echo "$VCPKG_ROOT" >> $GITHUB_PATH

          echo "Current PATH: $GITHUB_PATH"
          
          cd vcpkg

          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then  
            ./bootstrap-vcpkg.sh -disableMetrics
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then  
            ./bootstrap-vcpkg.sh -disableMetrics
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then 
            ./bootstrap-vcpkg.bat -disableMetrics
          fi
          
          cd ..

      - name: Build
        uses: LunarisLib/actions/CMake@master
        with:
          checkout: 'true'
          project_path: ./.examples/CMake/
          artifact_name: ${{ matrix.os }}_PROJECT

      - name: Upload artifacts to see what's going on
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.os }}-artifact
          path: build
          include-hidden-files: 'true'