name: CMake action build example test

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install libcurl
        shell: bash
        run: |  
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then  
            sudo apt install libcurl4-openssl-dev  
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then  
            brew install curl  
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then 
            choco install -y curl
            echo "C:\ProgramData\chocolatey\bin" >> $env:GITHUB_PATH
            ls -aRl
          fi

      - name: Build
        uses: LunarisLib/actions/CMake@master
        with:
          checkout: 'true'
          project_path: ./.examples/CMake/
          artifact_name: ${{ matrix.os }}_PROJECT
