name: CMake action build example test

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

env:
  PROJECT_PATH: "./.examples/CMake"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    steps:

      - name: Build
        uses: LunarisLib/actions/CMake@master
        with:
          checkout: 'true'
          project_path: ${{ env.PROJECT_PATH }}
          artifact_name: ${{ matrix.os }}_PROJECT
          use_vcpkg: 'true'