name: CMake action build example test

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

env:
  PROJECT_PATH: "./.examples/CMake"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ] # [ windows-latest, ubuntu-latest, macos-latest ]
    steps:

      - name: Build
        uses: LunarisLib/actions/CMake@experimental
        with:
          checkout: 'true'
          project_path: ${{ env.PROJECT_PATH }}
          artifact_name: ${{ matrix.os }}_PROJECT
          use_vcpkg: 'true'

      - name: Upload artifacts to see what's going on
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.os }}-artifact
          path: build
          include-hidden-files: 'true'